#!/usr/bin/env python3
"""Build the TGO Brands static site.

    python3 build.py              # writes ./dist
    python3 build.py --out DIR    # writes somewhere else

Standard library only. Every page is pre-rendered for both locales
(/ and /zh/), with clean directory URLs, a sitemap carrying hreflang pairs,
robots.txt and llms.txt. Deploy the output folder to any static host.
"""
import argparse
import hashlib
import json
import shutil
from pathlib import Path

import templates as T

ROOT = Path(__file__).resolve().parent
LANGS = ('en', 'zh')


def load(lang):
    return json.loads((ROOT / 'content' / f'{lang}.json').read_text(encoding='utf-8'))


def routes(c):
    """(page key, brand index or None, title, description) for every page."""
    out = [('home', None, c['meta']['title'], c['meta']['description'])]
    suffix = c['meta']['suffix']
    for key, section in (('what', 'what'), ('brands', 'brands'), ('founders', 'founders'),
                         ('markets', 'markets'), ('insights', 'insights'), ('partner', 'partner'),
                         ('contact', 'contact')):
        out.append((key, None, f'{c["nav"][key]} — {suffix}', c[section]['sub']))
    for i, b in enumerate(c['brands']['items']):
        out.append(('brand', i, f'{b["name"]} — {suffix}', b['pos']))
    return out


def page_path(lang, page, i, c):
    slug = c['brands']['items'][i]['slug'] if page == 'brand' else None
    return T.href(lang, page, slug)


def write(out, url_path, html):
    target = out / url_path.lstrip('/') / 'index.html'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(html, encoding='utf-8')


MARKER = '.tgo-build'


def build(out):
    if out.exists() and any(out.iterdir()):
        if not (out / MARKER).exists():
            raise SystemExit(f'{out} is not empty and is not a previous build; refusing to overwrite it')
        shutil.rmtree(out)
    assets = out / 'assets'
    assets.mkdir(parents=True)
    (out / MARKER).write_text('generated by build.py — safe to delete\n', encoding='utf-8')

    static = ROOT / 'static'
    for f in static.iterdir():
        shutil.copy2(f, assets / f.name)
    version = hashlib.sha1(b''.join((static / n).read_bytes() for n in ('site.css', 'site.js'))).hexdigest()[:10]

    content = {lang: load(lang) for lang in LANGS}
    sitemap = []
    count = 0
    for lang in LANGS:
        c = content[lang]
        other = 'zh' if lang == 'en' else 'en'
        for page, i, title, desc in routes(c):
            path = page_path(lang, page, i, c)
            alt = page_path(other, page, i, content[other])
            body = T.page_brand(c, lang, i) if page == 'brand' else T.PAGES[page](c, lang)
            write(out, path, T.document(c, lang, page, body, path, alt, title, desc, version))
            count += 1
            if lang == 'en':
                sitemap.append((path, alt))

    urls = ''.join(
        f'''  <url><loc>{T.SITE}{p}</loc>
    <xhtml:link rel="alternate" hreflang="en" href="{T.SITE}{p}"/>
    <xhtml:link rel="alternate" hreflang="zh-CN" href="{T.SITE}{z}"/>
  </url>
  <url><loc>{T.SITE}{z}</loc>
    <xhtml:link rel="alternate" hreflang="en" href="{T.SITE}{p}"/>
    <xhtml:link rel="alternate" hreflang="zh-CN" href="{T.SITE}{z}"/>
  </url>
''' for p, z in sitemap)
    (out / 'sitemap.xml').write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
        f'{urls}</urlset>\n', encoding='utf-8')
    (out / 'robots.txt').write_text(f'User-agent: *\nAllow: /\n\nSitemap: {T.SITE}/sitemap.xml\n', encoding='utf-8')
    (out / 'llms.txt').write_text(llms(content['en']), encoding='utf-8')
    (out / 'favicon.svg').write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#1d1d1f"/>'
        '<text x="32" y="40" text-anchor="middle" font-family="-apple-system,Helvetica,Arial,sans-serif" font-weight="700" '
        'font-size="22" fill="#f5f5f7">TGO</text></svg>\n', encoding='utf-8')
    return count


def llms(c):
    """A plain-text summary for AI agents, built from the same English copy."""
    lines = [
        '# TGO Brands',
        '',
        '> TGO Brands Limited is a Hong Kong holding company that brings Chinese consumer-electronics '
        'brands into Pakistan, India, the Philippines and the UAE: distribution, brand building, '
        'market entry and certification, sourcing, and on-the-ground market survey trips.',
        '',
        c['home']['premise'][2],
        '',
        '## Pages',
        '',
    ]
    for key in ('what', 'brands', 'founders', 'markets', 'insights', 'partner', 'contact'):
        section = c[key]
        lines.append(f'- [{c["nav"][key]}]({T.SITE}{T.href("en", key)}): {section["sub"]}')
    lines += ['', '## Brands', '']
    for b in c['brands']['items']:
        lines.append(f'- [{b["name"]}]({T.SITE}{T.href("en", "brand", b["slug"])}): {b["cat"]}. {b["pos"]}')
    lines += ['', '## Founders', '']
    for p in c['founders']['people']:
        lines.append(f'- {p["name"]} ({p["city"]}): {p["role"]}')
    lines += ['', '## Contact', '', '- hello@tgobrands.com', f'- Chinese site: {T.SITE}/zh/', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--out', default=str(ROOT / 'dist'), help='output directory (default: ./dist)')
    args = ap.parse_args()
    n = build(Path(args.out).resolve())
    print(f'built {n} pages into {args.out}')
